apiVersion: v1
kind: ConfigMap
metadata:
  name: mirrord-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
data:
  agent-config.yaml: |-
    {{- if and (.Values.agent.image) (kindIs "string" .Values.agent.image) }}
    image: "{{ .Values.agent.image }}"
    {{- else }}
    image:
      {{- if .Values.agent.image.registry }}
      registry: "{{ .Values.agent.image.registry }}"
      {{- end }}
      {{- if .Values.agent.image.tag}}
      tag: "{{ .Values.agent.image.tag }}"
      {{- end }}
    {{- end }}
    {{- if .Values.operator.imagePullSecrets }}
    image_pull_secrets:
    {{- range .Values.operator.imagePullSecrets }}
    - {{ toYaml . }}
    {{- end }}
    {{- end }}
    {{- if .Values.agent.extraConfig }}
    {{- .Values.agent.extraConfig | toYaml | nindent 4 }}
    {{- end }}
