name: CI
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.yaml"
  pull_request:
    branches: [main]
    paths:
      - "**.yaml"

jobs:
  sanity:
    runs-on: ubuntu-latest
    name: helm-sanity debug
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.1.0
      - run: helm template mirrord-operator --set license.key=secret --debug
